Revert "[artifactory] Use build/api/client to upload debug symbols."
This reverts commit 08d6470c4694967aeebd41f4547eb3c7cd57fd43.

Reason for revert: This breaks some smart-integration builders due to prebuilt binaries that breakpad fails to process.

Original change's description:
> [artifactory] Use build/api/client to upload debug symbols.
>
> This CL modifies artifactory to call the build/api/client
> "export_last_build_debug_symbols" to generate the debug
> symbol files to upload to cloud storage.
>
> The command also generates breakpad symbols, using
> multiple concurrent processes, which takes a few
> minutes on infra builders.
>
> GSYM symbols are not generated for now, as enabling
> this feature results in errors from llvm-gsymutil that
> look like:
>
> ```
> ERROR: DWARF conversion failed: : no functions to encode
> ```
>
> When processing certain input files.
>
> - Add a small denylist to debug_symbols.py to work-around
>   a Breakpad dump_syms crash for a small set of riscv64
>   binaries. See https://fxbug.dev/445670194
>
> NO_IFTTT=analyzer_does_no_recognize_change_in_ThenChange_list
>
> Bug: 445670194
> Bug: 399498301
> Change-Id: I15f5d5ff48219f9dd8b4fd3765f1fb9ad9d155ce
> Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1362473
> Reviewed-by: David Fang <fangism@google.com>
> Reviewed-by: Oliver Newman <olivernewman@google.com>
> Commit-Queue: David Turner <digit@google.com>
> Reviewed-by: Clayton Wilkinson <wilkinsonclay@google.com>

Bug: 445670194
Bug: 399498301
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I46f661c6612d4ab68fce11c5a3ba170c1717f75e
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1371483
Reviewed-by: RubberStamper 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Commit-Queue: David Turner <digit@google.com>