[superproject] Roll llvm-project/libc [libc] Fix compilation on 32-bit systems
This fixes the following compilation error: no known conversion from 'off_t *'
(aka 'long long *') to 'long' for 5th argument.

Since pointers are 32-bit long anyway, casting it to long shouldn't be a
problem. Tested on rv32.

Reviewed By: sivachandra

Differential Revision: https://reviews.llvm.org/D157792

GitOrigin-RevId: 52bf83abe4336c868becffdf4861cbc512c54182
Original-Revision: 4cc81ad6c3cf2fc4908b7d99f3cfa2c38b25c685
Roller-URL: https://ci.chromium.org/b/8772576287182290705
CQ-Do-Not-Cancel-Tryjobs: true
Change-Id: I8c41472855d9958e33cefbaebae65ab34d311b6c