Revert "[artifactory] Use build/api/client to upload debug symbols."
This reverts commit 3bec6caa8ef2ac02f4035664bdc70466f328ac74.

Reason for revert: breaks some smart display builders. See https://fuchsia-review.googlesource.com/c/fuchsia/+/1380784/5
which fails when generating breakpad symbols for some prebuilt
binaries.

Original change's description:
> [artifactory] Use build/api/client to upload debug symbols.
>
> This is a reland of [1] which was reverted due to MacOS related
> issues that have since been fixed.
>
> This CL modifies artifactory to call the build/api/client
> "export_last_build_debug_symbols" to generate the debug
> symbol files to upload to cloud storage.
>
> The command also generates breakpad symbols, using
> multiple concurrent processes, which takes a few
> minutes on infra builders.
>
> GSYM symbols are not generated for now, as enabling
> this feature results in errors from llvm-gsymutil that
> look like:
>
> ```
> ERROR: DWARF conversion failed: : no functions to encode
> ```
>
> When processing certain input files.
>
> - Add a small denylist to debug_symbols.py to work-around
>   a Breakpad dump_syms crash for a small set of riscv64
>   binaries. See https://fxbug.dev/445670194
>
> NO_IFTTT=analyzer_does_no_recognize_change_in_ThenChange_list
>
> Run-All-Tests: true
> Bug: 445670194
> Bug: 399498301
> [1]: https://fuchsia-review.googlesource.com/c/fuchsia/+/1362473
>
> Change-Id: I648306e2b2bbc08c385aaa9ece3a94265f833883
> Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1377761
> Reviewed-by: Aaron Wood <aaronwood@google.com>
> Reviewed-by: Clayton Wilkinson <wilkinsonclay@google.com>
> Commit-Queue: David Turner <digit@google.com>

Bug: 445670194
Bug: 399498301
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Ica2c371bfb37ba8438d09cbbd540a9e0f7bf08e5
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1379962
Commit-Queue: David Turner <digit@google.com>
Reviewed-by: RubberStamper 🤖 <android-build-ayeaye@system.gserviceaccount.com>