[superproject] Roll fuchsia [virtualization] Remove redundant libc imports.
This removes compiler errors with the message below. The errors started
showing up when the unused-imports Rust warning was promoted to a build
failure.

    error: the item `libc` is imported redundantly
     --> ../../src/virtualization/tests/virtio_gpu_test_util/src/linuxfb.rs:8:5
      |
    8 |     libc,
      |     ^^^^ the item `libc` is already defined by prelude
      |
      = note: requested on the command line with `-D unused-imports`

Test: fx build (no behavior changes)
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1006492
Original-Revision: 899d3bd2684b6d2c839ab53305a1bd667ae1fd2e
GitOrigin-RevId: 9f6308a03c5fca41b479dc55eb992ef34c58f541
Roller-URL: https://ci.chromium.org/b/8749222336192509585
CQ-Do-Not-Cancel-Tryjobs: true
Change-Id: Ica14d57d130465c8d91b70d6e5a9f939eb4abaae