[connectivity] network conformance test errors when tun/tap is not set up
Instead of spinning forever, if the tun/tap interface is not set up
we immediately error with:

====== Choosing FFX target: TestEmulatorWorksWithFfx-Nodename ======
    emulator_test.go:94: tun/tap device 'qemu' not found. To create
    one, run:

        $ sudo ip tuntap add dev qemu mode tap user $USER
        $ sudo ip link set qemu up
Stopped daemon.

Change-Id: I62212ce8909b08b825ff9a164b738a271078edae
--- FAIL: TestEmulatorWorksWithFfx (0.14s)
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1376945
Commit-Queue: Aidan Wolter <awolter@google.com>
Fuchsia-Auto-Submit: Aidan Wolter <awolter@google.com>
Reviewed-by: Bruno Dal Bo <brunodalbo@google.com>