[roll] Roll third_party/pigweed Revert "pw_trace_tokenized: Use InlineVarLenEntryQueue for trace buffer"
This reverts commit 8d47bd657be092b08a50ee2835a4ad4af9cbec42.

Reason for revert: Fetching trace data via pw_transfer fails with error:
pw_transfer.client.Error: Transfer 1 failed with status Status.INTERNAL

Original change's description:
> pw_trace_tokenized: Use InlineVarLenEntryQueue for trace buffer
>
> Original-Bug: 437155622
> Change-Id: Ic32231e879232076c8a52325ccf7f316422386c5
> Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/316736
> Reviewed-by: Wyatt Hepler <hepler@google.com>
> Presubmit-Verified: CQ Bot Account <pigweed-scoped@luci-project-accounts.iam.gserviceaccount.com>
> Tests-Not-Needed: Aaron Green <aarongreen@google.com>
> Lint: Lint 🤖 <android-build-ayeaye@system.gserviceaccount.com>
> Commit-Queue: Aaron Green <aarongreen@google.com>

# Not skipping CQ checks because original CL landed > 1 day ago.

Original-Bug: 437155622
Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/338592
Presubmit-Verified: CQ Bot Account <pigweed-scoped@luci-project-accounts.iam.gserviceaccount.com>
Original-Revision: ea90565a22d14385b600eae9d962fbe2de92f225

Rolled-Repo: https://fuchsia.googlesource.com/third_party/pigweed.googlesource.com/pigweed/pigweed
Rolled-Commits: c679abdcc8b4d4..ea90565a22d143
Roller-URL: https://cr-buildbucket.appspot.com/build/8699836512345688241
CQ-Do-Not-Cancel-Tryjobs: true
Change-Id: I4c7d13a3169bdaf8606638fd1cb6b53d129aeae9
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1404576
Commit-Queue: GI Roller <global-integration-roller@fuchsia-infra.iam.gserviceaccount.com>