[build] Add //build/ninja_implicit_inputs:manifest target.
Since GN currently never writes header files to the Ninja
build plan, these file paths are only visible from the Ninja
deps log *after* a build. This makes them invisible to Bazel
actions that invoke Ninja sub-builds, breaking incremental
correctness if they change.

To fix this, this CL adds metadata to each C++ target type
wrapper in BUILDCONFIG.gn, then performs their collection
in //build/ninja_implicit_inputs:manifest to generate
a manifest file at `gn gen` time listing them.

The result will be used later by a Bazel repository rule
(e.g. ninja_subbuild_repository()) to generate BUILD.bazel
files containing filegroup() targets covering the list of
all possible source input paths that may require
re-launching sub-build actions.

See README.md file for more details.

This CL also comes with a new script that can be
launched locally after a build to compute the set of
unknown implicit inputs (e.g. missing header definitions,
see https://fxbug.dev/462397407) from a set of root GN labels
or Ninja targets. For example, running:

```
python3 build/ninja_implicit_inputs/check_tool.py \
    --build \
    //zircon/public/sysroot_sdk
```

Generates a report that currently says:

```
ERROR: The following 249 GN targets use undeclared source inputs:

//build/bazel/host:bazel_root_targets
    third_party/boringssl/src/crypto/fipsmodule/aes/aes.cc.inc
    third_party/boringssl/src/crypto/fipsmodule/aes/aes_nohw.cc.inc
    third_party/boringssl/src/crypto/fipsmodule/aes/key_wrap.cc.inc
    third_party/boringssl/src/crypto/fipsmodule/aes/mode_wrappers.cc.inc
    ...

//zircon/kernel/lib/arch:_hwreg_header.tool.gen-riscv64-system-asm(//build/toolchain:host_x64)
    zircon/kernel/lib/arch/include/lib/arch/hwreg.h
    zircon/kernel/lib/arch/include/lib/arch/riscv64/system.h
    ...

...

//zircon/third_party/ulib/musl/src/passwd:passwd(//sdk/lib/c:user.libc_x64)
    zircon/third_party/ulib/musl/src/internal/libc.h
    zircon/third_party/ulib/musl/src/internal/limits.h
    zircon/third_party/ulib/musl/src/passwd/nscd.h
    zircon/third_party/ulib/musl/src/passwd/pwf.h
    ...

...
```

To fix this, future CLs will fix GN C++ target definitions
to provide the correct or missing header declarations.

Bug: 377233505
Bug: 462397407
Change-Id: I56b73d8d30e0410f06282914dbfd541919d8790a
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1433577
Reviewed-by: Jay Zhuang <jayzhuang@google.com>
Commit-Queue: David Turner <digit@google.com>