[beads][rust] Fix mypy errors in comparison scripts and deps
Note I'm switching a lot of list to Sequence because list is invariant,
which doesn't work well with type unions (e.g. str | Path), I'm seeing
mypy errors like:

```
build/api/ninja_artifacts.py:89: error:
Argument 1 to "run_command" of "CommandRunner" has incompatible type
"list[str]"; expected "list[str | PathLike[Any]]"  [arg-type]
                [str(self.ninja), "-C", str(self.build_dir)] + cmd,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
build/api/ninja_artifacts.py:89: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
build/api/ninja_artifacts.py:89: note: Consider using "Sequence" instead, which is covariant
````

Bug: 478707341
Change-Id: If57f30f404d65cc569682c2a112debaf7a397986
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1575074
Commit-Queue: Jay Zhuang <jayzhuang@google.com>
Reviewed-by: David Turner <digit@google.com>