[fho] Report that errors are coming from proc macro
Previously, fho would emit errors like this if there was a problem in
the generated define:

```
error: this lint expectation is unfulfilled
  --> ../../src/developer/ffx/plugins/config/src/lib.rs:31:10
   |
31 |     ctx: EnvironmentContext,
   |          ^^^^^^^^^^^^^^^^^^
   |
   = note: TryFromEnv associated error type may be Infallible
   = note: `-D unfulfilled-lint-expectations` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(unfulfilled_lint_expectations)]`

error: aborting due to 1 previous error
```

Thats because the error span was not being marked as coming from the
proc macro definition. With this change errors will now include that the
error came from the inside of the macro.

Change-Id: Ia303152d882e951be02165dc0eef49277f09aac5
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1787917
Fuchsia-Auto-Submit: Erick Tryzelaar <etryzelaar@google.com>
Commit-Queue: Erick Tryzelaar <etryzelaar@google.com>
Reviewed-by: Colin Nelson <colnnelson@google.com>