[bazel_sdk] Fix license fail message formatting
Correct the string formatting in the `fail` call when a dependency
of `applicable_licenses` does not provide `LicenseInfo`. It was
incorrectly using `+` instead of `%`, which would fail to format
the target into the error message with the following error:

  Error: unsupported binary operation: string + Target

Change-Id: Ic929b89cf769e778ff18e24e3f1792da6a6a6964
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1645534
Commit-Queue: Jay Zhuang <jayzhuang@google.com>
Reviewed-by: Darren Chan <chandarren@google.com>
Fuchsia-Auto-Submit: Jay Zhuang <jayzhuang@google.com>