[roll] Roll third_party/curl [build] Suppress -Wunused-but-set-variable in curl
This patch suppresses -Wunused-but-set-variable warning in
curl third party code that does not comply with.

The code that causes the issue is as the following:
../../third_party/curl/lib/dotdot.c:57:10: error: variable 'clen' set
but not used

Original-Bug: 96333
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/third_party/curl/+/662543
Original-Revision: 8b8fae33340186877a65950c2bf1f87d2e641109

Rolled-Repo: https://fuchsia.googlesource.com/third_party/curl
Rolled-Commits: 5f484ccbad9be0..8b8fae33340186
Roller-URL: https://cr-buildbucket.appspot.com/build/8705179167478604945
CQ-Do-Not-Cancel-Tryjobs: true
Change-Id: Ib1f595a9882d9092ee1f235ea134f16bfd2cac51
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1357894