[roll] Roll third_party/perfetto Fix trace processor build with bazel (#6161)
When building `@perfetto//:trace_processor` with bazel, the following 2
errors occur:

1.  Generated symbols are not found:

    ```
external/perfetto+/src/trace_processor/plugins/wattson/plugin.cc:97:9:
error: use of undeclared identifier 'kCpu2DCurvesData'; did you mean
'kCpu1DCurvesData'?
       97 |         kCpu2DCurvesData.data(), kCpu2DCurvesData.size()));
          |         ^~~~~~~~~~~~~~~~
          |         kCpu1DCurvesData

bazel-out/k8-opt/bin/external/perfetto+/src/trace_processor/plugins/wattson/cpu_1d_curves.h:26:44:
note: 'kCpu1DCurvesData' declared here
       26 | inline constexpr std::array<uint8_t, 2510> kCpu1DCurvesData{
          |                                            ^
external/perfetto+/src/trace_processor/plugins/wattson/plugin.cc:97:34:
error: use of undeclared identifier 'kCpu2DCurvesData'; did you mean
'kCpu1DCurvesData'?
       97 |         kCpu2DCurvesData.data(), kCpu2DCurvesData.size()));
          |                                  ^~~~~~~~~~~~~~~~
          |                                  kCpu1DCurvesData

bazel-out/k8-opt/bin/external/perfetto+/src/trace_processor/plugins/wattson/cpu_1d_curves.h:26:44:
note: 'kCpu1DCurvesData' declared here
       26 | inline constexpr std::array<uint8_t, 2510> kCpu1DCurvesData{
          |                                            ^
    ...
    ```
2. Compiler fails to find `zlib.h`, or finds the wrong `zlib.h`:

    ```
In file included from
external/perfetto+/src/trace_processor/trace_summary/summary.cc:55:
external/+_repo_rules2+gcc_lib/sysroot/usr/include/zlib.h:1332:31:
error: expected ';' after top level declarator
1332 | ZEXTERN int ZEXPORTVA gzprintf Z_ARG((gzFile file, const char
*format, ...));
          |                               ^
    ```

Error 1 happens when building perfetto as a module. Bzlmod uses '+' in
canonical repository names (e.g., 'perfetto+'), which propagates into
the generated header guard macros. Since '+' is not a valid character
for C++ preprocessor identifiers, the compiler truncates the macro name
at '+', leading to collisions. This PR adds extra sanitization to
include guards and replaces all illegal characters.

Error 2 was due to the zlib BUILD file containing a wrong include path,
which causes the compiler to fallback to one from the sysroot. Our
sysroot contains a very old `zlib.h` and is incompatible. This PR fixes
the missing include path. Further more, the
`CHROMIUM_ZLIB_NO_CHROMECONF` macro need to be propagated to any
downstream target that consumes `zlib.h` to keep a consistent zlib
config.
Original-Revision: b04b400e6dda095054c134ab6ca7bc382c500ac3

Rolled-Repo: https://fuchsia.googlesource.com/third_party/github.com/google/perfetto
Rolled-Commits: 4054aa0d03dd04..b04b400e6dda09
Roller-URL: https://cr-buildbucket.appspot.com/build/8679690267386749089
CQ-Do-Not-Cancel-Tryjobs: true
Change-Id: If22191ffcd3402d7d404cb5c13b45a7d1f647c3a
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1642375
Commit-Queue: global-integration-roller@fuchsia-infra.iam.gserviceaccount.com <global-integration-roller@fuchsia-infra.iam.gserviceaccount.com>